definitions:
  db.SubUser:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
  db.SubsFull:
    properties:
      subs:
        items:
          $ref: '#/definitions/db.SubUser'
        type: array
    type: object
info:
  contact: {}
paths:
  /api/subscription:
    delete:
      consumes:
      - application/json
      description: Удаляет подписку по user_id
      parameters:
      - description: ID пользователя для удаления
        example: "123"
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Подписка удалена
        "400":
          description: ID не указан
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Удалить подписку
      tags:
      - subscriptions
    get:
      consumes:
      - application/json
      description: Возвращает список всех подписок
      produces:
      - application/json
      responses:
        "200":
          description: Список всех подписок
          schema:
            $ref: '#/definitions/db.SubsFull'
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Получить все подписки
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Добавляет новую подписку в базу данных
      parameters:
      - description: Данные новой подписки
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/db.SubUser'
      produces:
      - application/json
      responses:
        "200":
          description: ID созданной подписки
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Пустое тело запроса
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Создать новую подписку
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Обновляет данные существующей подписки
      parameters:
      - description: Обновлённые данные подписки
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/db.SubUser'
      produces:
      - application/json
      responses:
        "200":
          description: Обновлённая подписка
          schema:
            $ref: '#/definitions/db.SubUser'
        "400":
          description: Пустое тело запроса
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Обновить подписку
      tags:
      - subscriptions
  /api/subscription_id:
    get:
      consumes:
      - application/json
      description: Возвращает информацию о подписке по user_id
      parameters:
      - description: ID пользователя
        example: "123"
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ
          schema:
            $ref: '#/definitions/db.SubUser'
        "400":
          description: ID не указан
          schema:
            type: string
        "404":
          description: Подписка не найдена
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Получить подписку по ID
      tags:
      - subscriptions
  /api/subscription_summary:
    get:
      consumes:
      - application/json
      description: Возвращает общую сумму подписок за указанный период с возможностью
        фильтрации
      parameters:
      - description: Дата начала в формате MM-YYYY
        example: 01-2026
        in: query
        name: startdate
        required: true
        type: string
      - description: Дата окончания в формате MM-YYYY
        example: 07-2026
        in: query
        name: enddate
        required: true
        type: string
      - description: ID пользователя для фильтрации
        example: "123"
        in: query
        name: user_id
        type: string
      - description: Название сервиса для фильтрации
        example: Netflix
        in: query
        name: service
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ с суммой
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Неверный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить сумму подписок за период
      tags:
      - subscriptions
swagger: "2.0"
